---
spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
cds:
  data-source.auto-config.enabled: false
  security.mock.users:
  - name: klaus
    password: pass_klaus
  - name: mia
    password: pass_mia
  - name: sabine
    password: pass_sabine
    roles:
        - Administrators